### PR TITLE
fixes #20

### LINKED ISSUE #20: url() action only accepts string
URL action actually accepts a text where you can embed variables inside. But current implementation of  `url()` only works for literal strings.

So, this does not work: 

```
@a = "http://google.com"
@b = url(a)
``` 
Currently, this gets generated with the code above:

Screen Shot 2023-09-04 at 2 11 27 PM

### PR DESCRIPTION
**Pull request by erenyenigul**

### CODE REVIEW

File: actions_std.go [hunk 1]
```diff
@@ -2644,9 +2641,9 @@ func scriptingActions() {
 					value:    true,
 				},
 				{
-					key:      "WFURLActionURL",
+					key: 	"WFURLActionURL",
```
Comment (electrikmilk) [inline actions_std.go:2644]: Please remove whitespace changes if possible.

File: actions_std.go [hunk 2]
```diff
@@ -2644,9 +2641,9 @@ func scriptingActions() {
...
 					dataType: Array,
-					value:    urlItems,
+					value: urlItems,
```
Comment (electrikmilk) [inline actions_std.go:2646]: Please remove whitespace changes if possible.

File: actions_std.go [hunk 3]
```diff
@@ -2632,10 +2632,7 @@ func scriptingActions() {
 		make: func(args []actionArgument) []plistData {
 			var urlItems []plistData
 			for _, item := range args {
-				urlItems = append(urlItems, plistData{
-					dataType: Text,
-					value:    item.value,
-				})
+				urlItems = append(urlItems, attachmentValues("", item.value.(string), Text),)
```
Comment (electrikmilk) [inline actions_std.go:2635]: Just a redundant comma at the end of the arguments for `attachmentValues()`

**Review by electrikmilk — CHANGES_REQUESTED** [review]
Just a suggestion and a couple of nitpicks about the removal of whitespace. Otherwise, LGTM and good catch. Thanks for your contribution!

File: actions_std.go (hunk 3 above)
Comment (electrikmilk) [reply actions_std.go:2635]: Also, I think using this here might be a bit cleaner so we don't need to coerse the value if we don't have to.

```suggestion
				urlItems = append(urlItems, paramValue("", arg, String, Text))
```

File: actions_std.go [hunk 4]
```diff
@@ -2790,9 +2787,9 @@ func scriptingActions() {
 					value:    true,
 				},
 				{
-					key:      "WFURLActionURL",
+					key: 	"WFURLActionURL",
```
Comment (electrikmilk) [inline actions_std.go:2790]:
```suggestion
					key:      "WFURLActionURL",
```

File: actions_std.go [hunk 5]
```diff
@@ -2790,9 +2787,9 @@ func scriptingActions() {
...
 					dataType: Array,
-					value:    urlItems,
+					value: urlItems,
```
Comment (electrikmilk) [inline actions_std.go:2792]:
```suggestion
					value:    urlItems,
```

**Review by electrikmilk — APPROVED** [review]
Applied suggested changes to PR, thanks for your contribution!
